version: "3.7"

services:
  postgresserver:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=football_manager_db
    expose:
      - "5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web-api:
    image: pedrmunhoz/football-manager-web-api:1.0.5
    environment:
      ServerDbConnectionString: "Host=postgresserver;Port=5432;Database=football_manager_db;Username=postgres;Password=123456;Pooling=false;"
    ports:
      - "8090:80"
    links:
      - postgresserver
    depends_on:
      - "postgresserver"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"

volumes:
  pgdata:


networks:
  internal:
